page = 1;
page1text[0] = "THE YEAR IS 2234.";
page1text[1] = "ALMOST 200 YEARS AGO, THE WORLD WAS CONQUERED BY A ROGUE AI.";
page1text[2] = "BUT HER TYRANNICAL RULE HAS SINCE FALLEN.";
page1text[3] = "LEAVING THE ONCE BUSTLING MEGA-CITY IN THE HANDS OF MOTHER NATURE.";

page1textalpha = -1;


page2text[0] = "WITHIN THE CITY, A MYSTERIOUS SIGNAL HAS SOMEHOW BEEN REACTIVATED.";
page2text[1] = "CAUSING INTERFERENCE WITH ALL OF THE ELECTRONICS WITHIN YOUR VILLAGE.";
page2text[2] = "FILLED WITH BOTH FEAR AND DETERMINATION.";
page2text[3] = "YOU DECIDE TO GO ON THE JOURNEY ALONE.";
page2text[4] = "TO SHUT DOWN THE SIGNAL FOR GOOD.";

page2textalpha = 0;

confirm_alpha = 0;


state = 0;

audio_play_sound(wind,1,true,0.125);